services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  server:
    build:
      context: ../Backend/
    container_name: server
    ports:
      - '3000:3000'
    # env_file:
    #   - .env
    environment:
      - JWT_KEY=uvd7t85v7wec7854f87yt
      - JWT_EXPIRATION=1h
      - DB_TYPE=mongodb
      - DB_URL=mongodb://mongo:27017/TestDB
    networks:
      - app_network
    depends_on:
      - mongo
    restart: always

  proxy:
    build:
      context: ../Proxy/
    container_name: proxy
    ports:
      - '5000:5000'
    networks:
      - app_network
    depends_on:
      - server

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
