export const errors = {
  jwtKeyMissing: 'JWT_KEY must be defined',
  dbTypeUndefined: 'DB_TYPE must be defined',
  mySqlVariablesUndefined: 'MySql variables must be defined',
  dbUrlUndefined: 'DB_URL must be defined',
  dbTypeInvalid: 'Invalid DB_TYPE',
  mongoDbConnectionFailed: 'Error connecting to the MongoDb database: ',
  mySqlConnectionFailed: 'Error connecting to the MySql database: ',
  internalServerError: 'Internal server error',
  userExists: 'User already exists',
  userNotFound: 'User not found',
  userCouldNotBeCreated: 'User could not be created',
  invalidPassword: 'Invalid password',
  invalidId: 'Invalid id',
  invalidName: 'Invalid name',
  invalidData: 'Invalid data',
  invalidEmail: 'Invalid email',
  noTokenProvided: 'Access Denied: No token provided',
  invalidToken: 'Access Denied: Invalid token',
};
